EmployeeManagement/Models/BloodGrp.cs
namespace EmployeeManagement.Models
{
    public enum BloodGrp
    {
        Ap,
        Bp,
        ABp,
        ABn,
        An,
        Bn,
        Op,
        On
    }
}

EmployeeManagement/Models/DepartementEnum.cs
namespace EmployeeManagement.Models
{
    public enum DepartementEnum
    {
        Developer,
        HR,
        Accountant,
        Manager
    }
}

EmployeeManagement/Models/EmployeeModel.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmployeeManagement.Models
{
    public class EmployeeModel
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ContactEmail { get; set; }
        public string City { get; set; }
        public int Age { get; set; }
        public RoleModel EmpRole { get; set; }
        public double Salary { get; set; }
        public string PhotoURL { get; set; }
    }
}

EmployeeManagement/Models/EmployeeRegisterModel.cs
using System.ComponentModel.DataAnnotations;

namespace EmployeeManagement.Models
{
    public class EmployeeRegisterModel
    {
        [Key]
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        [EmailAddress]
        public string Email { get; set; }
        public DepartementEnum Departement { get; set; }
        public BloodGrp BloodGroup { get; set; }
        public string MotherName { get; set; }
        public string FatherName { get; set; }
        public string ContactNo { get; set; }
    }
}

EmployeeManagement/Models/ErrorViewModel.cs
namespace EmployeeManagement.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmployeeManagement/Models/RoleModel.cs
namespace EmployeeManagement.Models
{
    public enum RoleModel
    {
        Developer,
        HR,
        Manager,
        Accountant
    }
}

EmployeeManagement/Controllers/EmployeeController.cs
using EmployeeManagement.InterfacesAndSqlRepos;
using EmployeeManagement.Models;
using EmployeeManagement.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeManagement.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeCRUD cRUD;
        private readonly IWebHostEnvironment webHostEnvironment;

        public EmployeeController(IEmployeeCRUD _cRUD, IWebHostEnvironment _webHostEnvironment)
        {
            this.cRUD = _cRUD;
            this.webHostEnvironment = _webHostEnvironment;
        }

        public IActionResult GetEmployee(int id)
        {
            var employee = cRUD.GetEmployee(id);
            return View(employee);
        }

        public IActionResult AllEmployees()
        {
            var employees = cRUD.GetAll();
            return View(employees);
        }

        [HttpGet]
        public async Task<ViewResult> AddEmployee(bool isSuccess = false, int prodId = 0)
        {
            var model = new EmployeeViewModel();
            ViewBag.IsSuccess = isSuccess;
            ViewBag.ProductId = prodId;
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        // Bind attribute is used because it was not taking IFormFile Photos from view.
        public async Task<IActionResult> AddEmployee([Bind("FirstName, LastName, ContactEmail, City, Age, EmpRole, Salary, Photos")] EmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Photos != null)
                {
                    string folder = "EmployeesImages/cover/";
                    model.PhotoURL = await UploadImage(folder, model.Photos);
                }
                int Id = await cRUD.AddNewEmployee(model);
                if (Id > 0)
                {
                    return RedirectToAction(nameof(AddEmployee), new { isSuccess = true, prodId = Id });
                }
            }
            return View();
        }

        private async Task<string> UploadImage(string folderPath, IFormFile file)
        {
            folderPath += Guid.NewGuid().ToString() + "_" + file.FileName;
            string serverFolder = Path.Combine(webHostEnvironment.WebRootPath, folderPath);
            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
            return "/" + folderPath;
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            EmployeeModel model = cRUD.GetEmployee(Id);
            EmployeeViewModel upEmployee = new EmployeeViewModel
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                ContactEmail = model.ContactEmail,
                City = model.City,
                Age = model.Age,
                EmpRole = model.EmpRole,
                Salary = model.Salary
            };
            return View(upEmployee);
        }
        [HttpPost]
        public IActionResult Edit(EmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {
                var employee = cRUD.GetEmployee(model.Id);
                if (employee != null)
                {
                    employee.FirstName = model.FirstName;
                    employee.LastName = model.LastName;
                    employee.ContactEmail = model.ContactEmail;
                    employee.City = model.City;
                    employee.Age = model.Age;
                    employee.EmpRole = model.EmpRole;
                    employee.Salary = model.Salary;
                    EmployeeModel upEmployee = cRUD.Update(employee);
                }
                return RedirectToAction("GetEmployee");
            }
            return View();
        }

        public IActionResult Delete(int id)
        {
            cRUD.Delete(id);
            return RedirectToAction("AllEmployees");
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

EmployeeManagement/Controllers/EmployeeRegisterController.cs
using EmployeeManagement.ApplicationDbContext;
using EmployeeManagement.InterfacesAndSqlRepos;
using EmployeeManagement.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeManagement.Controllers
{
    public class EmployeeRegisterController : Controller
    {
        private readonly DatabaseContext context;
        private readonly IEmployeeRegisterCRUD cRUD;

        public EmployeeRegisterController(DatabaseContext _context, IEmployeeRegisterCRUD _cRUD)
        {
            context = _context;
            cRUD = _cRUD;
        }

        // Add Method.
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(EmployeeRegisterModel model)
        {
            var employee = cRUD.Add(model);
            context.SaveChanges();
            return View(model);
        }

        public IActionResult GetEmployee(int id)
        {
            var employee = cRUD.GetEmployee(id);
            return View(employee);
        }

        public IActionResult Index()
        {
            var employees = context.EmployeesRegister;
            return View(employees);
        }

    }
}

EmployeeManagement/Controllers/HomeController.cs
using EmployeeManagement.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmployeeManagement.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmployeeManagement/Views/Employee/AddEmployee.cshtml
@model EmployeeManagement.ViewModel.EmployeeViewModel

@{
    ViewData["Title"] = "AddEmployee";
}

<h1>AddEmployee</h1>
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

<hr />
<div class="row">
    <div class="col-md-4">
        @if (ViewBag.IsSuccess == true)
        {
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>Congratulations</strong> You have added new Product successfully. <br />
                Click <a asp-controller="Employee" asp-action="GetEmployee" asp-route-id="@ViewBag.Id">here</a> to view the details
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        <form asp-action="AddEmployee" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactEmail" class="control-label"></label>
                <input asp-for="ContactEmail" class="form-control" />
                <span asp-validation-for="ContactEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmpRole" class="control-label"></label>
                <select asp-for="EmpRole" class="custom-select mr-sm-2"
                        asp-items="Html.GetEnumSelectList<RoleModel>()">

                    <option value="">Please Select</option>

                </select>
                <span asp-validation-for="EmpRole" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Photos" class="control-label"></label>
                <div class="mb-3">
                    <label for="formFile" class="form-label">Default file input example</label>
                    <input class="form-control" asp-for="Photos" id="formFile">
                </div>
                <span asp-validation-for="Photos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>

            <div class="flex justify-center">
                <div class="mb-3 w-96">
                    <label for="formFileDisabled" class="form-label inline-block mb-2 text-gray-700">Disabled file input example</label>
                    <input class="form-control block w-full-3 py-1.5 text-base font-normal text-gray-700 bg-gray-100 bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" type="file" id="formFileDisabled" disabled>
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

EmployeeManagement/Views/Employee/AllEmployees.cshtml
@model IEnumerable<EmployeeManagement.Models.EmployeeModel>

@{
    ViewData["Title"] = "AllEmployees";
}

<h1>AllEmployees</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@*<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmpRole)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salary)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmpRole)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                
            </td>
        </tr>
}
    </tbody>
</table>
*@

@foreach(var item in Model)
{
    <section class="bg-gray-800 dark:bg-gray-900 rounded-lg">
        <div class="container px-6 py-10 mx-auto">
            <h1 class="text-3xl font-semibold text-gray-800 capitalize lg:text-4xl dark:text-white">From the blog</h1>

            <div class="grid grid-cols-1 gap-8 mt-8 md:mt-16 md:grid-cols-2">

                <div class="lg:flex">
                    <img class="object-cover w-full h-56 rounded-lg lg:w-64" src="@item.PhotoURL" alt="">

                    <div class="flex flex-col justify-between py-6 lg:mx-6">
                        <a href="#" class="text-xl font-semibold text-blue-800 hover:underline dark:text-white ">
                            @item.FirstName
                        </a>
                        <p class="text-xl font-semibold text-blue-800 hover:underline dark:text-white ">@item.ContactEmail</p>
                        <p class ="text-xl font-semibold text-blue-800 hover:underline dark:text-white ">@item.Age</p>
                        <p class="text-xl font-semibold text-blue-800 hover:underline dark:text-white ">@item.City</p>

                        <span class="text-sm text-gray-500 dark:text-gray-300">On: 20 October 2019</span>
                        <span class="text-sm text-gray-500 dark:text-gray-300">
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                            <a asp-action="GetEmployee" asp-route-id="@item.Id">Details</a>
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </span>
                    </div>
                </div>

            </div>
        </div>
    </section>
}

EmployeeManagement/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EmployeeManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/output.css" asp-append-version="true" />

    <script src="https://unpkg.com/flowbite@1.5.3/dist/flowbite.js"></script>
    <link rel="stylesheet" href="~/EmployeeManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmployeeManagement</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
        <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>
        </ul>
        </div>
        </div>
        </nav>*@

        <!-- This is an example component -->
        <div class="max-w-2xl mx-auto">

            <nav class="border-gray-200 px-2 mb-10">
                <div class="container mx-auto flex flex-wrap items-center justify-between">
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="flex">
                        <svg class="h-10 mr-3" width="51" height="70" viewBox="0 0 51 70" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0)"><path d="M1 53H27.9022C40.6587 53 51 42.7025 51 30H24.0978C11.3412 30 1 40.2975 1 53Z" fill="#76A9FA"></path><path d="M-0.876544 32.1644L-0.876544 66.411C11.9849 66.411 22.4111 55.9847 22.4111 43.1233L22.4111 8.87674C10.1196 8.98051 0.518714 19.5571 -0.876544 32.1644Z" fill="#A4CAFE"></path><path d="M50 5H23.0978C10.3413 5 0 15.2975 0 28H26.9022C39.6588 28 50 17.7025 50 5Z" fill="#1C64F2"></path></g><defs><clipPath id="clip0"><rect width="51" height="70" fill="white"></rect></clipPath></defs></svg>
                        <span class="self-center text-lg font-semibold whitespace-nowrap">Emma</span>
                    </a>
                    <div class="flex md:order-2">

                        @*Search Bar.*@
                        @*<div class="relative mr-3 md:mr-0 hidden md:block">
                        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <svg class="w-5 h-5 text-gray-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
                        </div>
                        <input type="text" id="email-adress-icon" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2" placeholder="Search...">
                        </div>*@

                        <button data-collapse-toggle="mobile-menu-3" type="button" class="md:hidden text-gray-400 hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-300 rounded-lg inline-flex items-center justify-center" aria-controls="mobile-menu-3" aria-expanded="false">
                            <span class="sr-only">Open main menu</span>
                            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
                            <svg class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                        </button>
                    </div>
                    <div class="hidden md:flex justify-between items-center w-full md:w-auto md:order-1" id="mobile-menu-3">
                        <ul class="flex-col md:flex-row flex md:space-x-8 mt-4 md:mt-0 md:text-sm md:font-medium">
                            <li>
                                <a asp-area="" asp-controller="Home" asp-action="Index" class="bg-blue-700 md:bg-transparent text-white block pl-3 pr-4 py-2 md:text-blue-700 md:p-0 rounded" aria-current="page">Home</a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="Employee" asp-action="AddEmployee" class="text-gray-700 hover:bg-gray-50 border-b border-gray-100 md:hover:bg-transparent md:border-0 block pl-3 pr-4 py-2 md:hover:text-blue-700 md:p-0">Employee</a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="EmployeeRegister" asp-action="Create" class="text-gray-700 hover:bg-gray-50 border-b border-gray-100 md:hover:bg-transparent md:border-0 block pl-3 pr-4 py-2 md:hover:text-blue-700 md:p-0">EmployeeRegister</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

        </div>

        <script src="~/js/navNew.js"></script>
    </header>

    @* Made a div with flex so renderbody content display adjacent to sidemenu.*@
    <div class="flex">
        <aside class="w-64" aria-label="Sidebar">
            <div class="overflow-y-auto py-4 px-3 bg-gray-50 rounded dark:bg-gray-800">
                <ul class="space-y-2">
                    <li>
                        <button type="button" class="flex items-center p-2 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700" aria-controls="dropdown-example" data-collapse-toggle="dropdown-example">
                            <svg aria-hidden="true" class="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 group-hover:text-gray-900 dark:text-gray-400 dark:group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 2a4 4 0 00-4 4v1H5a1 1 0 00-.994.89l-1 9A1 1 0 004 18h12a1 1 0 00.994-1.11l-1-9A1 1 0 0015 7h-1V6a4 4 0 00-4-4zm2 5V6a2 2 0 10-4 0v1h4zm-6 3a1 1 0 112 0 1 1 0 01-2 0zm7-1a1 1 0 100 2 1 1 0 000-2z" clip-rule="evenodd"></path></svg>
                            <span class="flex-1 ml-3 text-left whitespace-nowrap" sidebar-toggle-item>E-commerce</span>
                            <svg sidebar-toggle-item class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                        </button>
                        <ul id="dropdown-example" class="hidden py-2 space-y-2">
                            <li>
                                <a asp-action="AddEmployee" asp-controller="Employee" class="flex items-center p-2 pl-11 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">Add Employee</a>
                            </li>
                            <li>
                                <a asp-action="AddEmployee" asp-controller="Employee" class="flex items-center p-2 pl-11 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">All Employees</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <button type="button" class="flex items-center p-2 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700" aria-controls="dropdown-example2" data-collapse-toggle="dropdown-example2">
                            <svg aria-hidden="true" class="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 group-hover:text-gray-900 dark:text-gray-400 dark:group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 2a4 4 0 00-4 4v1H5a1 1 0 00-.994.89l-1 9A1 1 0 004 18h12a1 1 0 00.994-1.11l-1-9A1 1 0 0015 7h-1V6a4 4 0 00-4-4zm2 5V6a2 2 0 10-4 0v1h4zm-6 3a1 1 0 112 0 1 1 0 01-2 0zm7-1a1 1 0 100 2 1 1 0 000-2z" clip-rule="evenodd"></path></svg>
                            <span class="flex-1 ml-3 text-left whitespace-nowrap" sidebar-toggle-item>EmployeeRegister</span>
                            <svg sidebar-toggle-item class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                        </button>
                        <ul id="dropdown-example2" class="hidden py-2 space-y-2">
                            <li>
                                <a asp-action="Create" asp-controller="EmployeeRegister" class="flex items-center p-2 pl-11 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">Add Employee</a>
                            </li>
                            <li>
                                <a asp-action="AddEmployee" asp-controller="EmployeeRegister" class="flex items-center p-2 pl-11 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">All Employees</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </aside>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    @*<footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2022 - EmployeeManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>